/**
 * Makkah and Madina hotel directory.
 *
 * HONESTY NOTES — read before editing:
 *
 * 1. Distances are APPROXIMATE and differ between sources because they are
 *    measured to different gates. Swissôtel Makkah is quoted anywhere from
 *    ~50 m (to the nearest Abraj Al-Bait entrance) to ~412 m (to the mataf).
 *    We therefore store a range-free "approx" figure plus the reference point,
 *    and the UI always renders the word "approx".
 * 2. Price bands are INDICATIVE off-peak nightly rates in PKR for a double
 *    room, converted loosely. Ramadan's last ten nights run several times
 *    these figures. Never quote these as a price to a customer.
 * 3. `photos` is intentionally EMPTY for every hotel. We do not hold licensed
 *    photography of these buildings, and generic stock or generated images
 *    are not acceptable for a named real property. The UI degrades to a
 *    typographic card when photos is empty. See docs/HOTEL-IMAGES.md.
 * 4. `officialUrl` is the hotel's or chain's own site so a customer can verify
 *    everything here themselves.
 */

export type HotelCity = 'makkah' | 'madina';

export interface Hotel {
  slug: string;
  name: string;
  city: HotelCity;
  /** Which cluster it sits in — this is what actually determines the walk. */
  zone: string;
  stars: 3 | 4 | 5;
  /** Approximate metres to the reference point below. */
  approxDistanceM: number;
  distanceReference: string;
  walkMinutes: number;
  /** Indicative off-peak PKR per night, double room. */
  priceFromPKR: number;
  services: string[];
  officialUrl: string;
  /** True where the property is commonly used in Nusuk-linked bookings. */
  commonForUmrahGroups: boolean;
  notes?: string;
  /** Licensed photography we actually hold. Empty until real photos exist. */
  photos: string[];
}

export const hotels: Hotel[] = [
  // ── MAKKAH · Abraj Al-Bait (Clock Tower) complex ──────────────────────────
  {
    slug: 'fairmont-makkah-clock-royal-tower',
    name: 'Fairmont Makkah Clock Royal Tower',
    city: 'makkah',
    zone: 'Abraj Al-Bait (Clock Tower)',
    stars: 5,
    approxDistanceM: 100,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 3,
    priceFromPKR: 95000,
    services: ['Haram-view rooms', 'Multiple restaurants', 'Prayer broadcast in room', 'Family rooms', '24h room service', 'Laundry'],
    officialUrl: 'https://www.fairmont.com/makkah/',
    commonForUmrahGroups: true,
    notes: 'Occupies the clock tower itself. The most recognisable address in Makkah and priced accordingly.',
    photos: [],
  },
  {
    slug: 'swissotel-makkah',
    name: 'Swissôtel Makkah',
    city: 'makkah',
    zone: 'Abraj Al-Bait (Clock Tower)',
    stars: 5,
    approxDistanceM: 150,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 4,
    priceFromPKR: 78000,
    services: ['Direct mall access', 'Buffet restaurant', 'Family rooms', 'Wheelchair access', 'Laundry', 'Prayer broadcast'],
    officialUrl: 'https://www.swissotel.com/hotels/makkah/',
    commonForUmrahGroups: true,
    notes: 'Sources quote anywhere from 50 m to 412 m depending on whether they measure to the mall entrance or the mataf.',
    photos: [],
  },
  {
    slug: 'swissotel-al-maqam-makkah',
    name: 'Swissôtel Al Maqam Makkah',
    city: 'makkah',
    zone: 'Abraj Al-Bait (Clock Tower)',
    stars: 5,
    approxDistanceM: 200,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 5,
    priceFromPKR: 72000,
    services: ['Buffet restaurant', 'Family and quad rooms', 'Direct mall access', 'Laundry', '24h reception'],
    officialUrl: 'https://www.swissotel.com/hotels/makkah-al-maqam/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'pullman-zamzam-makkah',
    name: 'Pullman ZamZam Makkah',
    city: 'makkah',
    zone: 'Abraj Al-Bait (Clock Tower)',
    stars: 5,
    approxDistanceM: 300,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 6,
    priceFromPKR: 62000,
    services: ['Buffet restaurant', 'Haram-view rooms', 'Family rooms', 'Laundry', 'Direct mall access'],
    officialUrl: 'https://all.accor.com/hotel/7297/index.en.shtml',
    commonForUmrahGroups: true,
    notes: 'The value option inside the complex; widely used for group bookings.',
    photos: [],
  },
  {
    slug: 'raffles-makkah-palace',
    name: 'Raffles Makkah Palace',
    city: 'makkah',
    zone: 'Abraj Al-Bait (Clock Tower)',
    stars: 5,
    approxDistanceM: 150,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 4,
    priceFromPKR: 140000,
    services: ['All-suite property', 'Butler service', 'Haram views', 'Fine dining', 'Private lounge'],
    officialUrl: 'https://www.raffles.com/makkah/',
    commonForUmrahGroups: false,
    notes: 'The most expensive address in the city. Rarely used for standard group packages.',
    photos: [],
  },
  {
    slug: 'movenpick-hajar-tower-makkah',
    name: 'Mövenpick Hotel & Residences Hajar Tower Makkah',
    city: 'makkah',
    zone: 'Abraj Al-Bait (Clock Tower)',
    stars: 5,
    approxDistanceM: 200,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 5,
    priceFromPKR: 68000,
    services: ['Buffet restaurant', 'Serviced residences', 'Family rooms', 'Direct mall access'],
    officialUrl: 'https://movenpick.accor.com/en/middle-east/saudi-arabia/makkah.html',
    commonForUmrahGroups: true,
    photos: [],
  },

  // ── MAKKAH · Jabal Omar ───────────────────────────────────────────────────
  {
    slug: 'conrad-makkah',
    name: 'Conrad Makkah',
    city: 'makkah',
    zone: 'Jabal Omar',
    stars: 5,
    approxDistanceM: 500,
    distanceReference: 'Haram third expansion',
    walkMinutes: 9,
    priceFromPKR: 74000,
    services: ['Wide family rooms', 'Multiple dining venues', 'Haram views', 'Shuttle within complex', 'Laundry'],
    officialUrl: 'https://www.hilton.com/en/hotels/jedcici-conrad-makkah/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'jabal-omar-marriott-makkah',
    name: 'Jabal Omar Marriott Hotel Makkah',
    city: 'makkah',
    zone: 'Jabal Omar',
    stars: 5,
    approxDistanceM: 550,
    distanceReference: 'Haram third expansion',
    walkMinutes: 10,
    priceFromPKR: 66000,
    services: ['Buffet and à la carte dining', 'Family rooms', 'Complex walkway to Haram', 'Laundry'],
    officialUrl: 'https://www.marriott.com/hotels/travel/jedjo-jabal-omar-marriott-hotel-makkah/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'hyatt-regency-makkah',
    name: 'Hyatt Regency Makkah Jabal Omar',
    city: 'makkah',
    zone: 'Jabal Omar',
    stars: 5,
    approxDistanceM: 550,
    distanceReference: 'Haram third expansion',
    walkMinutes: 10,
    priceFromPKR: 64000,
    services: ['Buffet restaurant', 'Family rooms', 'Covered walkway', 'Laundry', '24h reception'],
    officialUrl: 'https://www.hyatt.com/hyatt-regency/en-US/jedhr-hyatt-regency-makkah-jabal-omar',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'doubletree-jabal-omar-makkah',
    name: 'DoubleTree by Hilton Makkah Jabal Omar',
    city: 'makkah',
    zone: 'Jabal Omar',
    stars: 4,
    approxDistanceM: 600,
    distanceReference: 'Haram third expansion',
    walkMinutes: 11,
    priceFromPKR: 48000,
    services: ['Buffet restaurant', 'Family rooms', 'Complex walkway', 'Laundry'],
    officialUrl: 'https://www.hilton.com/en/hotels/jeddtdt-doubletree-makkah-jabal-omar/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'hilton-suites-makkah',
    name: 'Hilton Suites Makkah',
    city: 'makkah',
    zone: 'Jabal Omar / Ibrahim Al Khalil Road',
    stars: 5,
    approxDistanceM: 400,
    distanceReference: 'King Fahd Gate',
    walkMinutes: 7,
    priceFromPKR: 58000,
    services: ['All-suite rooms', 'Kitchenette in suites', 'Buffet restaurant', 'Family friendly', 'Laundry'],
    officialUrl: 'https://www.hilton.com/en/hotels/jedhshi-hilton-suites-makkah/',
    commonForUmrahGroups: true,
    notes: 'Commonly cited at about a five-minute walk to King Fahd Gate outside peak times.',
    photos: [],
  },
  {
    slug: 'address-jabal-omar-makkah',
    name: 'Address Jabal Omar Makkah',
    city: 'makkah',
    zone: 'Jabal Omar',
    stars: 5,
    approxDistanceM: 500,
    distanceReference: 'Haram third expansion',
    walkMinutes: 9,
    priceFromPKR: 82000,
    services: ['Haram-view suites', 'Multiple restaurants', 'Club lounge', 'Family rooms'],
    officialUrl: 'https://www.addresshotels.com/en/resorts/address-jabal-omar-makkah/',
    commonForUmrahGroups: false,
    photos: [],
  },
  {
    slug: 'anjum-hotel-makkah',
    name: 'Anjum Hotel Makkah',
    city: 'makkah',
    zone: 'Jabal Omar / Ibrahim Al Khalil Road',
    stars: 4,
    approxDistanceM: 450,
    distanceReference: 'Nearest Haram gate',
    walkMinutes: 8,
    priceFromPKR: 42000,
    services: ['Large buffet hall', 'Group check-in desks', 'Family and quad rooms', 'Laundry', 'Shuttle'],
    officialUrl: 'https://www.anjumhotelmakkah.com/',
    commonForUmrahGroups: true,
    notes: 'Built for volume — one of the most common choices for Pakistani group packages.',
    photos: [],
  },

  // ── MAKKAH · Ajyad and Misfalah ───────────────────────────────────────────
  {
    slug: 'dar-al-tawhid-intercontinental-makkah',
    name: 'Dar Al Tawhid InterContinental Makkah',
    city: 'makkah',
    zone: 'Ibrahim Al Khalil Road',
    stars: 5,
    approxDistanceM: 100,
    distanceReference: 'King Fahd Gate',
    walkMinutes: 3,
    priceFromPKR: 92000,
    services: ['Direct Haram access', 'Fine dining', 'Family rooms', 'Butler service', 'Laundry'],
    officialUrl: 'https://www.ihg.com/intercontinental/hotels/us/en/makkah/qcamk/hoteldetail',
    commonForUmrahGroups: true,
    notes: 'One of the closest properties to a Haram gate of any hotel in the city.',
    photos: [],
  },
  {
    slug: 'makkah-hotel-formerly-hilton',
    name: 'Makkah Hotel (formerly Makkah Hilton)',
    city: 'makkah',
    zone: 'Ibrahim Al Khalil Road',
    stars: 5,
    approxDistanceM: 150,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 4,
    priceFromPKR: 70000,
    services: ['Attached shopping centre', 'Buffet dining', 'Family rooms', 'Haram views', 'Laundry'],
    officialUrl: 'https://www.makkahhotel.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'dar-al-eiman-royal',
    name: 'Dar Al Eiman Royal Hotel',
    city: 'makkah',
    zone: 'Ajyad',
    stars: 4,
    approxDistanceM: 250,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 5,
    priceFromPKR: 38000,
    services: ['Buffet restaurant', 'Quad and family rooms', 'Group desks', 'Laundry', '24h reception'],
    officialUrl: 'https://www.daraleiman.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'dar-al-eiman-grand',
    name: 'Dar Al Eiman Grand Hotel',
    city: 'makkah',
    zone: 'Ajyad',
    stars: 4,
    approxDistanceM: 300,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 6,
    priceFromPKR: 35000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', 'Group handling'],
    officialUrl: 'https://www.daraleiman.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'elaf-kinda-makkah',
    name: 'Elaf Kinda Hotel Makkah',
    city: 'makkah',
    zone: 'Ibrahim Al Khalil Road',
    stars: 4,
    approxDistanceM: 300,
    distanceReference: 'King Fahd Gate',
    walkMinutes: 6,
    priceFromPKR: 40000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', 'Shuttle at peak times'],
    officialUrl: 'https://www.elafhotels.com.sa/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'elaf-ajyad-makkah',
    name: 'Elaf Ajyad Hotel Makkah',
    city: 'makkah',
    zone: 'Ajyad',
    stars: 4,
    approxDistanceM: 350,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 7,
    priceFromPKR: 36000,
    services: ['Buffet restaurant', 'Quad rooms', 'Laundry', 'Group handling'],
    officialUrl: 'https://www.elafhotels.com.sa/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'le-meridien-makkah',
    name: 'Le Méridien Makkah',
    city: 'makkah',
    zone: 'Jabal Al Kaaba / Ajyad',
    stars: 5,
    approxDistanceM: 700,
    distanceReference: 'Nearest Haram gate',
    walkMinutes: 12,
    priceFromPKR: 52000,
    services: ['Buffet restaurant', 'Family rooms', 'Shuttle service', 'Laundry'],
    officialUrl: 'https://www.marriott.com/hotels/travel/qcalm-le-meridien-makkah/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'voco-makkah',
    name: 'voco Makkah',
    city: 'makkah',
    zone: 'Ibrahim Al Khalil Road',
    stars: 4,
    approxDistanceM: 600,
    distanceReference: 'Nearest Haram gate',
    walkMinutes: 11,
    priceFromPKR: 44000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', 'Shuttle'],
    officialUrl: 'https://www.ihg.com/voco/hotels/us/en/reservation',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'infinity-hotel-makkah',
    name: 'Infinity Hotel Makkah',
    city: 'makkah',
    zone: 'Misfalah',
    stars: 4,
    approxDistanceM: 800,
    distanceReference: 'Nearest Haram gate',
    walkMinutes: 13,
    priceFromPKR: 32000,
    services: ['Buffet restaurant', 'Family rooms', 'Free shuttle', 'Laundry'],
    officialUrl: 'https://www.infinityhotelmakkah.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'al-kiswah-towers',
    name: 'Al Kiswah Towers Hotel',
    city: 'makkah',
    zone: 'Kudai / Misfalah',
    stars: 3,
    approxDistanceM: 2000,
    distanceReference: 'Haram',
    walkMinutes: 28,
    priceFromPKR: 22000,
    services: ['Frequent free shuttle', 'Large buffet hall', 'Quad rooms', 'Built for groups'],
    officialUrl: 'https://www.alkiswahtowers.com/',
    commonForUmrahGroups: true,
    notes: 'Shuttle-dependent. Popular for economy packages where budget matters more than the walk.',
    photos: [],
  },
  {
    slug: 'makarem-ajyad-makkah',
    name: 'Makarem Ajyad Makkah Hotel',
    city: 'makkah',
    zone: 'Ajyad',
    stars: 4,
    approxDistanceM: 400,
    distanceReference: 'King Abdul Aziz Gate',
    walkMinutes: 7,
    priceFromPKR: 39000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', '24h reception'],
    officialUrl: 'https://www.makarem.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'emaar-grand-makkah',
    name: 'Emaar Grand Hotel Makkah',
    city: 'makkah',
    zone: 'Ibrahim Al Khalil Road',
    stars: 4,
    approxDistanceM: 500,
    distanceReference: 'Nearest Haram gate',
    walkMinutes: 9,
    priceFromPKR: 41000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', 'Shuttle'],
    officialUrl: 'https://www.emaarhotels.com.sa/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'rotana-jabal-omar-makkah',
    name: 'M Hotel Makkah by Millennium (Jabal Omar area)',
    city: 'makkah',
    zone: 'Jabal Omar',
    stars: 4,
    approxDistanceM: 900,
    distanceReference: 'Nearest Haram gate',
    walkMinutes: 15,
    priceFromPKR: 37000,
    services: ['Buffet restaurant', 'Family rooms', 'Shuttle', 'Laundry'],
    officialUrl: 'https://www.millenniumhotels.com/',
    commonForUmrahGroups: true,
    photos: [],
  },

  // ── MADINA · Central Zone (facing the Prophet's Mosque) ───────────────────
  {
    slug: 'the-oberoi-madina',
    name: 'The Oberoi Madina',
    city: 'madina',
    zone: 'Central Zone — south plaza',
    stars: 5,
    approxDistanceM: 80,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 2,
    priceFromPKR: 76000,
    services: ['All-suite property', 'Fine dining', 'Butler service', 'Family suites', 'Laundry'],
    officialUrl: 'https://www.oberoihotels.com/hotels-in-madina/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'dar-al-taqwa-madina',
    name: 'Dar Al Taqwa Hotel Madina',
    city: 'madina',
    zone: 'Central Zone — south plaza',
    stars: 5,
    approxDistanceM: 100,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 2,
    priceFromPKR: 66000,
    services: ['Direct plaza access', 'Buffet restaurant', 'Family rooms', 'Laundry'],
    officialUrl: 'https://www.daraltaqwa.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'anwar-al-madinah-movenpick',
    name: 'Anwar Al Madinah Mövenpick Hotel',
    city: 'madina',
    zone: 'Central Zone — south plaza',
    stars: 5,
    approxDistanceM: 150,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 3,
    priceFromPKR: 58000,
    services: ['Attached commercial centre', 'Large buffet', 'Family and quad rooms', 'Group handling', 'Laundry'],
    officialUrl: 'https://movenpick.accor.com/en/middle-east/saudi-arabia/madinah.html',
    commonForUmrahGroups: true,
    notes: 'Very widely used for Pakistani group packages because of its size and group facilities.',
    photos: [],
  },
  {
    slug: 'pullman-zamzam-madina',
    name: 'Pullman ZamZam Madina',
    city: 'madina',
    zone: 'Central Zone — south plaza',
    stars: 5,
    approxDistanceM: 200,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 4,
    priceFromPKR: 54000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', '24h reception'],
    officialUrl: 'https://all.accor.com/hotel/8579/index.en.shtml',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'madinah-hilton',
    name: 'Madinah Hilton',
    city: 'madina',
    zone: 'Central Zone — south plaza',
    stars: 5,
    approxDistanceM: 150,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 3,
    priceFromPKR: 60000,
    services: ['Attached shopping centre', 'Buffet dining', 'Family rooms', 'Laundry'],
    officialUrl: 'https://www.hilton.com/en/hotels/medhitw-madinah-hilton/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'intercontinental-dar-al-iman-madinah',
    name: 'InterContinental Dar Al Iman Madinah',
    city: 'madina',
    zone: 'Central Zone — south plaza',
    stars: 5,
    approxDistanceM: 120,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 3,
    priceFromPKR: 68000,
    services: ['Direct plaza access', 'Fine dining', 'Family rooms', 'Laundry', 'Butler service'],
    officialUrl: 'https://www.ihg.com/intercontinental/hotels/us/en/madinah/medha/hoteldetail',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'shaza-al-madina',
    name: 'Shaza Al Madina',
    city: 'madina',
    zone: 'Central Zone — north',
    stars: 5,
    approxDistanceM: 250,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 5,
    priceFromPKR: 56000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', 'Prayer broadcast'],
    officialUrl: 'https://www.shazahotels.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'frontel-al-harithia',
    name: 'Frontel Al Harithia Hotel',
    city: 'madina',
    zone: 'Central Zone — north',
    stars: 4,
    approxDistanceM: 300,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 5,
    priceFromPKR: 40000,
    services: ['Buffet restaurant', 'Family and quad rooms', 'Laundry', 'Group handling'],
    officialUrl: 'https://www.frontelhotels.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'millennium-al-aqeeq-madinah',
    name: 'Millennium Al Aqeeq Hotel Madinah',
    city: 'madina',
    zone: 'Central Zone — north',
    stars: 5,
    approxDistanceM: 400,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 7,
    priceFromPKR: 46000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', 'Shuttle at peak'],
    officialUrl: 'https://www.millenniumhotels.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'elaf-taiba-madina',
    name: 'Elaf Taiba Hotel Madina',
    city: 'madina',
    zone: 'Central Zone — north',
    stars: 4,
    approxDistanceM: 350,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 6,
    priceFromPKR: 38000,
    services: ['Buffet restaurant', 'Quad rooms', 'Laundry', 'Group desks'],
    officialUrl: 'https://www.elafhotels.com.sa/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'dallah-taibah-madina',
    name: 'Dallah Taibah Hotel',
    city: 'madina',
    zone: 'Central Zone — north',
    stars: 4,
    approxDistanceM: 300,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 5,
    priceFromPKR: 39000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', '24h reception'],
    officialUrl: 'https://www.dallahhotels.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'al-eiman-royal-madina',
    name: 'Al Eiman Royal Hotel Madina',
    city: 'madina',
    zone: 'Central Zone — west',
    stars: 4,
    approxDistanceM: 350,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 6,
    priceFromPKR: 34000,
    services: ['Buffet restaurant', 'Quad and family rooms', 'Group handling', 'Laundry'],
    officialUrl: 'https://www.aleimanhotels.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'madinah-movenpick-al-nabawi',
    name: 'Mövenpick Hotel Al Nabawi Madinah',
    city: 'madina',
    zone: 'Central Zone — east',
    stars: 5,
    approxDistanceM: 250,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 5,
    priceFromPKR: 52000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', 'Group facilities'],
    officialUrl: 'https://movenpick.accor.com/en/middle-east/saudi-arabia/madinah.html',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'taiba-front-hotel',
    name: 'Taiba Front Hotel',
    city: 'madina',
    zone: 'Central Zone — north',
    stars: 4,
    approxDistanceM: 200,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 4,
    priceFromPKR: 42000,
    services: ['Buffet restaurant', 'Family rooms', 'Laundry', 'Close to Ladies Gate'],
    officialUrl: 'https://www.taibahotels.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
  {
    slug: 'al-ansar-golden-madina',
    name: 'Al Ansar Golden Hotel',
    city: 'madina',
    zone: 'Central Zone — west',
    stars: 3,
    approxDistanceM: 450,
    distanceReference: "Prophet's Mosque courtyard",
    walkMinutes: 8,
    priceFromPKR: 26000,
    services: ['Buffet restaurant', 'Quad rooms', 'Budget group option', 'Laundry'],
    officialUrl: 'https://www.alansarhotels.com/',
    commonForUmrahGroups: true,
    photos: [],
  },
];

export function getHotel(slug: string): Hotel | undefined {
  return hotels.find((h) => h.slug === slug);
}

export function hotelsByCity(city: HotelCity): Hotel[] {
  return hotels
    .filter((h) => h.city === city)
    .sort((a, b) => a.approxDistanceM - b.approxDistanceM);
}

/** The four we lead with on the homepage: closest, group-friendly, well known. */
export function featuredHotels(city: HotelCity): Hotel[] {
  return hotelsByCity(city)
    .filter((h) => h.commonForUmrahGroups)
    .slice(0, 4);
}

export function formatDistance(h: Hotel): string {
  return h.approxDistanceM >= 1000
    ? `approx. ${(h.approxDistanceM / 1000).toFixed(1)} km`
    : `approx. ${h.approxDistanceM} m`;
}
